name             'cookBookFromBerks'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures cookBookFromBerks'
long_description 'Installs/Configures cookBookFromBerks'
version          '0.1.0'
